version: "3"

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=dockerplanner
      - POSTGRESQL_PASSWORD=dockerplanner
      - POSTGRESQL_DATABASE=apishoplanner
